### ISSUE TITLE
this project tested ubuntu linux?

### ISSUE THREAD

**Issue by yonghoonkwon** [Wehrdo/Tango_CUDA#1]
windows cuda din't run?
(when i tested on windows system, but compile error occurred on cuda)
![o](https://cloud.githubusercontent.com/assets/15377745/10926566/d072949c-82db-11e5-87fc-bdd3b51f5947.PNG)

my commandLine path is
 commandLine "E:/cuda/v7.0/bin/nvcc",
                    "-target-cpu-arch", "ARM",
                    "-include", "/SDK/android-ndk-r10d/platforms/android-19/arch-arm/usr/include/android/log.h",
                    "-ccbin", "arm-linux-gnueabihf-g++",
                    "--compiler-options", "\'-fPIC\'",
                    "-arch=sm_20",
                    "-m32",
                    "-c",
                    "src/main/jni/nativeCUDA.cu",
                    "-o", "src/main/jni/gpuCode.o"

Thanks in advance.

**Comment by Wehrdo** [comment]
It looks like you're using CUDA 7. The Tango only supports CUDA 6.0. (Maybe 6.5 with the new CodeWorks?). You can get the right CUDA from here: https://developer.nvidia.com/codeworks-android

Have you seen my blog post describing this in better detail? http://davidawehr.com/blog/?p=43
